FROM nginx:latest

#RUN mkdir -p /etc/nginx
#RUN mkdir -p /etc/ssl

RUN apt-get -y update
RUN apt-get install -y lsof
COPY docker/config/proxy/nginx.conf /etc/nginx/nginx.conf
COPY docker/config/ssl /etc/ssl

CMD ["nginx", "-g", "daemon off;"]
